name: Scheduled Full Deploy To Int

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ vars.INT_BRANCH }}
          fetch-depth: 0

      - name: Deploy full repository to ${{ vars.INT_ORG }} org
        uses: ./.github/actions/sf-deploy
        with:
          DRY_RUN: false
          TEST_LEVEL: RunLocalTests
          DEPLOY_TYPE: FULL
          DESTRUCIVE: false
          WAIT: 30
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_INT }}